### ISSUE TITLE
Laravel 8?

### ISSUE THREAD

**Issue by joserick** [mathieutu/laravel-json-syncer#14]
Will there be support for laravel 8?

![image](https://user-images.githubusercontent.com/15143699/111059642-cc0a0b00-845c-11eb-9ead-68b7b987abf5.png)

**Comment by mathieutu** [comment]
Hi.
Actually I think nothing will prevent the package for working with L8.

I'll let you make a PR updating the version in the composer.json and in tests matrix.

Thanks.

**Comment by mathieutu** [comment]
Here we go! We should be ok, feel free to raise an issue if you encounter some problems.
